variables:
  deploy_root: "/var/www/build/adminguide"

stages:
  - build
  - deploy
  - test

.review_template: &review_def
  only:
    - branches
  except:
    - master

.staging_template: &staging_def
  only:
    - master

.release_template: &release_def
  only:
    - /^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:$|-)/
  except:
    - branches

.artifacts_template: &artifacts_def
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    paths:
      - local/

.artifacts_review_template: &artifacts_review_def
  artifacts:
    <<: *artifacts_def
    expire_in: 1 days

.artifacts_staging_template: &artifacts_staging_def
  artifacts:
    <<: *artifacts_def
    expire_in: 2 weeks

.artifacts_release_template: &artifacts_release_def
  artifacts:
    <<: *artifacts_def
    paths:
      - local/
      - public/

.build_template: &build_def
  stage: build
  script:
    - &build_script |
      gitbook install
      gitbook build ./ local

.clean_template: &clean_def
  script:
    - &clean_script |
      deploy_dir="$deploy_root/$CI_COMMIT_REF_NAME"
      if [ -d "$deploy_dir/" ]; then rm -rf "$deploy_dir/"; fi

.deploy_template: &deploy_def
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://docs.bg.local/adminguide/$CI_COMMIT_REF_NAME/
    on_stop: cleanup
  variables:
    GIT_STRATEGY: none
  <<: *clean_def
  script:
    - *clean_script
    - &deploy_local_script |
      mkdir $deploy_dir
      /bin/cp --recursive --link ./local/* $deploy_root/$CI_COMMIT_REF_NAME/

.testing_template: &testing_def
  stage: test
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - /usr/bin/linkchecker https://docs.bg.local/adminguide/$CI_COMMIT_REF_NAME/ --no-status

build_review:
  <<: *review_def
  <<: *build_def
  <<: *artifacts_review_def

deploy_review:
  <<: *review_def
  <<: *deploy_def

testing_review:
  <<: *review_def
  <<: *testing_def

build_staging:
  <<: *staging_def
  <<: *build_def
  <<: *artifacts_staging_def

deploy_staging:
  <<: *staging_def
  <<: *deploy_def

testing_staging:
  <<: *staging_def
  <<: *testing_def

build_release:
  <<: *release_def
  <<: *build_def
  script: 
    - *build_script
    - config=`/usr/bin/jq -n --slurpfile orig ./book.json '$orig[] | .pluginsConfig."theme-loginom-website".counters_enabled = true'`
    - echo "$config" > ./book.json
    - gitbook build ./ public
  <<: *artifacts_release_def

deploy_release:
  <<: *release_def
  extends: .deploy_template
  environment:
    url: https://help.loginom.ru/adminguide
  script:
    - *clean_script
    - *deploy_local_script
    - ~/bin/deploy-production adminguide ./public

testing_release:
  <<: *release_def
  <<: *testing_def

cleanup:
  stage: deploy
  <<: *clean_def
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop